server:
  port: 8086

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/simform-invoicing-system?createDatabaseIfNotExist=true
    username: postgres
    password: Simform@123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      show-sql: false
      ddl-auto: create-drop
