server:
  port: 8086

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ec2-52-200-5-135.compute-1.amazonaws.com:5432/dqgeqofomepoh?createDatabaseIfNotExist=true
    username: kfvnvkrugmjvdu
    password: 215be6b2575249c7f55d07457b7e21febbbf09ac47ce39984042a70993141e0c
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      show-sql: false
      ddl-auto: update
